"""Shared write / ``--check`` runner for the reference-doc generators.

Every generator owns one directory under ``docs/reference/`` and supplies a
``render()`` callable returning ``{page file name: Markdown text}`` for that
directory. ``run()`` either writes the pages (removing orphan files left in
the directory) or, with ``--check``, compares them with the committed copies:

    exit 0  every page is current (or was written)
    exit 1  ``--check`` found a stale, missing or orphan page (summary on stderr)
    exit 2  could not run: ``code_indexer`` imported from another tree, a page
            over MAX_PAGE_LINES, a page name with a directory part, or a
            subdirectory inside the generated directory
"""

import argparse
import difflib
import re
import sys
from pathlib import Path
from typing import Callable, List, Mapping, Optional, Sequence

REPO_ROOT = Path(__file__).resolve().parents[2]

# Upper bound on diff lines printed by --check; the summary stays short.
MAX_DIFF_LINES = 40

# Project rule: no file may exceed 1000 lines.
MAX_PAGE_LINES = 1000

_WHITESPACE = re.compile(r"\s+")


class WrongTreeError(RuntimeError):
    """The imported code_indexer package does not belong to this repository."""


def generated_header(command: str) -> str:
    """One-line HTML comment marking a file as generated by ``command``."""
    return (
        f"<!-- Generated by `{command}` from code. Do not edit by hand; "
        "run that command to regenerate. -->"
    )


def md_cell(text: str) -> str:
    """Make ``text`` safe for one Markdown table cell.

    Whitespace (including newlines) collapses to single spaces and ``|`` is
    escaped everywhere. Outside inline code spans, backslashes and ``*`` are
    escaped (globs and regexes render literally) and ``<``/``>`` become
    entities so that placeholders such as ``<alias>`` are not swallowed as
    HTML tags.
    """
    collapsed = _WHITESPACE.sub(" ", text).strip()
    segments = collapsed.split("`")
    for index in range(0, len(segments), 2):  # even segments are outside code
        segments[index] = (
            segments[index]
            .replace("\\", "\\\\")
            .replace("*", "\\*")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
        )
    return "`".join(segments).replace("|", "\\|")


def check_package_location(package_file: Path, repo_root: Path) -> None:
    """Raise WrongTreeError unless ``package_file`` lives under ``repo_root/src``.

    The generators document the code they import; documenting another clone
    (for example an editable install pointing elsewhere) would be silent drift.
    """
    src_dir = (repo_root / "src").resolve()
    resolved = Path(package_file).resolve()
    if src_dir != resolved and src_dir not in resolved.parents:
        raise WrongTreeError(
            f"code_indexer was imported from {resolved.parent}, not from "
            f"{src_dir}. Run with PYTHONPATH={src_dir}."
        )


def _page_errors(pages: Mapping[str, str]) -> List[str]:
    errors = []
    for name, text in sorted(pages.items()):
        if name in ("", ".", "..") or Path(name).name != name:
            errors.append(f"page name {name!r} must be a plain file name")
        lines = len(text.splitlines())
        if lines > MAX_PAGE_LINES:
            errors.append(
                f"page {name} has {lines} lines (limit {MAX_PAGE_LINES}); "
                "split it in the generator"
            )
    return errors


def _diff(name: str, current: str, expected: str) -> List[str]:
    return list(
        difflib.unified_diff(
            current.splitlines(),
            expected.splitlines(),
            fromfile=f"{name} (committed)",
            tofile=f"{name} (generated)",
            lineterm="",
        )
    )


def _check(target_dir: Path, pages: Mapping[str, str], command: str) -> int:
    if not target_dir.is_dir():
        print(f"{target_dir} is missing. Run `{command}`.", file=sys.stderr)
        return 1
    problems: List[str] = []
    diff_lines: List[str] = []
    for name in sorted(pages):
        path = target_dir / name
        if not path.is_file():
            problems.append(f"missing: {name}")
            continue
        current = path.read_text(encoding="utf-8")
        if current != pages[name]:
            problems.append(f"stale: {name}")
            diff_lines += _diff(name, current, pages[name])
    for entry in sorted(target_dir.iterdir()):
        if entry.name not in pages:
            problems.append(f"orphan: {entry.name}")
    if not problems:
        print(f"{target_dir.name}/ is current ({len(pages)} pages).")
        return 0
    print(f"{target_dir} is out of date. Run `{command}`.", file=sys.stderr)
    for line in problems + diff_lines[:MAX_DIFF_LINES]:
        print(line, file=sys.stderr)
    if len(diff_lines) > MAX_DIFF_LINES:
        print(
            f"... ({len(diff_lines) - MAX_DIFF_LINES} more diff lines)", file=sys.stderr
        )
    return 1


def _write(target_dir: Path, pages: Mapping[str, str]) -> int:
    if target_dir.is_dir():
        nested = [e.name for e in target_dir.iterdir() if e.is_dir()]
        if nested:
            print(
                f"ERROR: {target_dir} is generated and must not contain "
                f"directories: {', '.join(sorted(nested))}",
                file=sys.stderr,
            )
            return 2
    target_dir.mkdir(parents=True, exist_ok=True)
    for entry in sorted(target_dir.iterdir()):
        if entry.name not in pages:
            entry.unlink()
            print(f"Removed orphan {entry}")
    for name, text in sorted(pages.items()):
        (target_dir / name).write_text(text, encoding="utf-8")
    longest = max(len(text.splitlines()) for text in pages.values())
    print(f"Wrote {len(pages)} pages to {target_dir} (longest {longest} lines)")
    return 0


def run(
    argv: Optional[Sequence[str]],
    *,
    target_dir: Path,
    render: Callable[[], Mapping[str, str]],
    command: str,
) -> int:
    """Write ``target_dir`` from ``render()``, or verify it with ``--check``."""
    parser = argparse.ArgumentParser(description=f"Generate {target_dir.name}/.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 when a committed page is stale, missing or orphaned",
    )
    args = parser.parse_args(list(argv) if argv is not None else None)

    import code_indexer

    try:
        check_package_location(Path(code_indexer.__file__), REPO_ROOT)
    except WrongTreeError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    if target_dir.is_symlink():
        print(
            f"ERROR: {target_dir} is a symlink; the generated directory must be "
            "a real directory",
            file=sys.stderr,
        )
        return 2
    try:
        pages = render()
    except ValueError as exc:
        print(f"ERROR: could not render {target_dir.name}/: {exc}", file=sys.stderr)
        return 2
    errors = _page_errors(pages)
    if errors or not pages:
        for error in errors or ["render() produced no pages"]:
            print(f"ERROR: {error}", file=sys.stderr)
        return 2
    if args.check:
        return _check(target_dir, pages, command)
    return _write(target_dir, pages)
