# ruff: noqa: F811
"""Files whose RESOLVED location is inside the repository's ``.git`` are
refused or hidden exactly like missing files by SCIP (generation and
queries), file listings and ``regex_search`` with an explicit path.

Driven through a real app (repo_url_userinfo_env). The golden clone gains
more committed-symlink shapes into ``.git`` (absolute, chained, nested) and
a real SCIP index generated by scip-python.

Hosts, usernames and secrets are neutral placeholders.
"""

from __future__ import annotations

import json
import shutil
import sqlite3
from pathlib import Path
from typing import Any, Dict, List

import pytest
from fastapi.testclient import TestClient

from tests.unit.server.repo_url_userinfo_env import (  # noqa: F401 - fixtures
    GIT_DIR_LINK,
    GIT_FILE_LINKS,
    GLOBAL_ALIAS,
    OK_PY_LINK,
    SECRET,
    USER,
    USER_ACTIVATION,
    activate_for_user,
    app,
    assert_no_userinfo,
    client,
    get,
    golden_clone_path,
    mcp_call,
)

EXTRA_LINKS = ("abs.py", "chain.py", "sub/x.py")
GIT_BACKED = (*GIT_FILE_LINKS, *EXTRA_LINKS)


@pytest.fixture(scope="module")
def clone(app: Any) -> Path:
    """The golden clone with the extra symlink shapes and a pyproject."""
    repo = golden_clone_path(app)
    if not (repo / "abs.py").is_symlink():
        (repo / "abs.py").symlink_to(repo / ".git" / "config")
        (repo / "chain.py").symlink_to("link.py")
        (repo / "sub").mkdir()
        (repo / "sub" / "x.py").symlink_to("../.git/config")
        (repo / "pyproject.toml").write_text('[project]\nname = "example"\n')
    return repo


@pytest.fixture
def activation(app: Any, clone: Path, monkeypatch: pytest.MonkeyPatch) -> str:
    activate_for_user(app, monkeypatch)
    return USER_ACTIVATION


def _body(client: TestClient, app: Any, tool: str, args: Dict[str, Any]) -> str:
    return json.dumps(mcp_call(client, app, USER, tool, args))


def _assert_hidden(body: str) -> None:
    assert_no_userinfo(body)
    for name in GIT_BACKED:
        assert name not in body, (name, body)


# ----------------------------------------------------------------------- SCIP


@pytest.fixture(scope="module")
def scip_db(clone: Path) -> Path:
    if shutil.which("scip-python") is None:
        pytest.skip("scip-python is not installed")
    from code_indexer.scip.generator import SCIPGenerator

    result = SCIPGenerator(clone).generate()
    assert result.successful_projects >= 1, result
    dbs = list((clone / ".code-indexer" / "scip").rglob("index.scip.db"))
    assert len(dbs) == 1, dbs
    return dbs[0]


def test_scip_generation_stores_no_git_backed_document(scip_db: Path) -> None:
    with sqlite3.connect(scip_db) as conn:
        paths = {r[0] for r in conn.execute("SELECT relative_path FROM documents")}
    assert "main.py" in paths, paths
    assert not paths & set(GIT_BACKED), paths


@pytest.mark.parametrize("tool", ["scip_definition", "scip_references", "scip_context"])
def test_scip_queries_never_return_git_backed_content(
    client: TestClient, app: Any, scip_db: Path, tool: str
) -> None:
    body = _body(client, app, tool, {"symbol": "url", "repository_alias": GLOBAL_ALIAS})
    _assert_hidden(body)
    found = _body(
        client,
        app,
        "scip_definition",
        {"symbol": "example", "repository_alias": GLOBAL_ALIAS},
    )
    assert "main.py" in found, found


def test_scip_source_reader_refuses_git_backed_files(
    clone: Path, scip_db: Path
) -> None:
    from code_indexer.scip.query.backends import DatabaseBackend

    backend = DatabaseBackend(scip_db, project_root=str(clone))
    for name in GIT_BACKED:
        assert backend._read_lines_within_root(clone / name) is None, name
    assert backend._read_lines_within_root(clone / "main.py") == ["example = 1"]


# ------------------------------------------------------------------- Listings


def test_mcp_listings_hide_git_backed_symlinks(
    client: TestClient, app: Any, activation: str
) -> None:
    for repo in (GLOBAL_ALIAS, activation):
        for tool, extra in (
            ("list_files", {}),
            ("browse_directory", {"recursive": True}),
        ):
            body = _body(client, app, tool, {"repository_alias": repo, **extra})
            assert OK_PY_LINK in body, body
            _assert_hidden(body)


def test_rest_listing_hides_git_backed_symlinks(
    client: TestClient, app: Any, activation: str
) -> None:
    for params in ({}, {"recursive": "true"}):
        listing = get(
            client, app, USER, f"/api/repos/{activation}/files", params=params
        )
        assert listing.status_code == 200, listing.text
        names: List[str] = [e["path"] for e in listing.json()["files"]]
        assert OK_PY_LINK in names, names
        assert GIT_DIR_LINK not in names, names
        assert not set(names) & set(GIT_BACKED), names


# --------------------------------------------------------------------- Regex


@pytest.mark.parametrize(
    "path", ["link.py", "chain.py", "abs.py", "sub/x.py", "gitdir"]
)
def test_regex_search_refuses_git_backed_paths_like_missing_paths(
    client: TestClient, app: Any, clone: Path, path: str
) -> None:
    def call(p: str) -> str:
        return _body(
            client,
            app,
            "regex_search",
            {"repository_alias": GLOBAL_ALIAS, "pattern": "url", "path": p},
        )

    refused = call(path)
    missing = call("missing-dir")
    _assert_hidden(refused.replace(json.dumps(path)[1:-1], "<path>"))
    assert refused.replace(path, "<path>") == missing.replace("missing-dir", "<path>")
    assert SECRET not in refused
