"""ActivityWatchdog: parent-side heartbeat reader + staleness evaluator.

Issue #1530, Priority 2 (parent-side half). Complements
`activity_heartbeat_writer.py` (the child-side writer). This module reads a
child's heartbeat file and decides -- via a pure, I/O-free function -- when
the reported activity indicates a genuine wedge, i.e. zero forward progress
for longer than an operator-configured threshold. It is consumed by
`progress_subprocess_runner.py`'s `run_with_popen_progress`, which owns the
actual Popen/polling loop and env-var wiring.

Bug #1218 invariant, non-negotiable: `evaluate_staleness` NEVER triggers on
total elapsed time alone. A job that ticks every few seconds for ten hours
must never trip this detector -- only a genuine, sustained absence of
forward progress does. Three independent signals feed it, all gated by the
SAME operator-configured threshold:

1. Absence past a grace period: the heartbeat file never appeared (or
   became unreadable) within `threshold_seconds` of process spawn -- fail-
   safe on absence (issue design point 4), not fail-open forever.
2. The beacon's own reported oldest-in-flight age (sourced from
   `ActivityBeacon.snapshot()`, written by `ActivityHeartbeatWriter`)
   exceeds the threshold -- the primary signal.
3. The heartbeat FILE's own mtime age exceeds the threshold -- defense-in-
   depth against a fully frozen process where even the background writer
   thread can no longer run (e.g. a GIL-level deadlock), which would
   otherwise leave a stale-but-never-updated "healthy" snapshot forever.

None of these three can ever fire from total elapsed time alone: signal 1
is gated on the FILE's absence, not the job's age; signals 2 and 3 are
gated on ages that reset to (near) zero on every genuine tick/write.

Fail-safe on absence, fail-open elsewhere: a missing/unreadable/corrupt
heartbeat file is NOT immediately treated as a wedge (the child may simply
not have started yet, or a transient read raced a write) -- it becomes
stale only once elapsed time since spawn exceeds the threshold.

`heartbeat_path` throughout this module is always an internal, node-local
path generated by this project's own code (the parent generates a fresh
UUID-based path under its own temp/data dir before spawning the child) --
never a path derived from untrusted external (HTTP/RPC) input.
`read_heartbeat_snapshot`'s actual security property is narrower and more
important for this use case: it must NEVER raise, regardless of what it
finds at that path or what garbage the file contains, so a transient read
failure (the child mid-write, a permissions blip, disk pressure, or even a
malformed/corrupt payload) degrades to "no data yet" rather than crashing
the parent's watchdog loop.
"""

from __future__ import annotations

import json
import logging
import os
import signal
import subprocess
import time
from dataclasses import dataclass
from typing import Optional

logger = logging.getLogger(__name__)

#: Grace period after SIGTERM before escalating to SIGKILL when a stale
#: subprocess's process group is terminated.
_SIGTERM_GRACE_SECONDS = 2.0


@dataclass(frozen=True)
class StalenessVerdict:
    """Why `evaluate_staleness` decided a subprocess is wedged."""

    reason: str
    label: Optional[str]
    age_seconds: Optional[float]
    pid: Optional[int]


def read_heartbeat_snapshot(path: str) -> Optional[dict]:
    """Read+parse the heartbeat JSON file at `path`. Never raises: returns
    None for absent/unreadable/non-JSON-object content (see module
    docstring for why absence is handled by the caller, not here).
    """
    try:
        with open(path) as f:
            data = json.load(f)
    except (OSError, ValueError) as exc:
        logger.debug(
            "ActivityWatchdog: could not read heartbeat file %s: %s", path, exc
        )
        return None
    if not isinstance(data, dict):
        logger.debug(
            "ActivityWatchdog: heartbeat file %s did not contain a JSON object",
            path,
        )
        return None
    return data


def _most_stale_label(snapshot: dict) -> Optional[str]:
    """Label of the in-flight entry with the largest numeric age_seconds,
    or None if there are no well-formed in-flight entries. Tolerates a
    malformed/corrupt `in_flight` list (non-list, non-dict items, missing
    or non-numeric `age_seconds`) by simply skipping bad entries -- never
    raises, matching this module's overall fail-safe contract.
    """
    in_flight = snapshot.get("in_flight")
    if not isinstance(in_flight, list):
        return None
    worst_label: Optional[str] = None
    worst_age = -1.0
    for item in in_flight:
        if not isinstance(item, dict):
            continue
        age = item.get("age_seconds")
        if not isinstance(age, (int, float)) or age <= worst_age:
            continue
        worst_age = age
        label = item.get("label")
        worst_label = label if isinstance(label, str) else None
    return worst_label


def evaluate_staleness(
    snapshot: Optional[dict],
    *,
    threshold_seconds: float,
    elapsed_since_spawn_seconds: float,
    heartbeat_mtime_age_seconds: Optional[float] = None,
) -> Optional[StalenessVerdict]:
    """Pure, I/O-free decision: None when healthy, else a `StalenessVerdict`.
    See the module docstring for the three staleness signals this checks.
    """
    if snapshot is None:
        if elapsed_since_spawn_seconds > threshold_seconds:
            return StalenessVerdict(
                reason="heartbeat_file_never_appeared_or_unreadable",
                label=None,
                age_seconds=elapsed_since_spawn_seconds,
                pid=None,
            )
        return None

    pid = snapshot.get("pid")
    pid = pid if isinstance(pid, int) else None

    oldest_age = snapshot.get("oldest_in_flight_age_seconds")
    if isinstance(oldest_age, (int, float)) and oldest_age > threshold_seconds:
        return StalenessVerdict(
            reason="stale_in_flight_operation",
            label=_most_stale_label(snapshot),
            age_seconds=float(oldest_age),
            pid=pid,
        )

    if (
        heartbeat_mtime_age_seconds is not None
        and heartbeat_mtime_age_seconds > threshold_seconds
    ):
        return StalenessVerdict(
            reason="heartbeat_file_not_updating",
            label=None,
            age_seconds=heartbeat_mtime_age_seconds,
            pid=pid,
        )

    return None


def terminate_process_group(proc: "subprocess.Popen") -> None:
    """SIGTERM the process group, wait a grace period, escalate to SIGKILL.
    Always blocks until the child is reaped.

    Deliberately DUPLICATED from
    `server/utils/cancellable_subprocess.py::_terminate_process_group`
    rather than imported -- but NOT for the import-budget reason first
    claimed here, which measurement disproves. Actual numbers: importing
    `server.utils.cancellable_subprocess` into a cold interpreter pulls 16
    modules (~48 ms), not "~70", and `cidx`'s own CLI already imports
    `code_indexer.server.utils` (config_manager, registry_factory,
    global_repos) today, so the marginal cost of importing it from here is
    exactly ONE module.

    The reason that does hold is layering: this module lives under
    `services/`, which the plain standalone CLI depends on, and that layer
    must not depend on `code_indexer.server` -- today's CLI import graph is
    an accident that a future import-budget cleanup (Bug #1468's own
    ambition) should be free to fix without dragging the indexing path
    back in. Messi Rule #4's three-strike rule permits this second copy of
    a ~15-line, stdlib-only algorithm (os/signal/subprocess, no
    project-specific dependencies). A THIRD occurrence must instead be
    extracted into the existing layer-neutral `code_indexer/utils/`
    package ("shared, layer-agnostic utilities importable by both CLI and
    server") and imported by all three.
    """
    try:
        pgid = os.getpgid(proc.pid)
    except ProcessLookupError:
        proc.wait()
        return

    try:
        os.killpg(pgid, signal.SIGTERM)
    except ProcessLookupError:
        proc.wait()
        return

    try:
        proc.wait(timeout=_SIGTERM_GRACE_SECONDS)
        return
    except subprocess.TimeoutExpired:
        pass

    try:
        os.killpg(pgid, signal.SIGKILL)
    except ProcessLookupError:
        pass
    proc.wait()


def _read_heartbeat_mtime_age(heartbeat_path: str) -> Optional[float]:
    """Age (seconds) of the heartbeat file's mtime, or None if it cannot
    be stat'd (routine during the bootstrap grace period).
    """
    try:
        return time.time() - os.path.getmtime(heartbeat_path)
    except OSError as exc:
        logger.debug(
            "ActivityWatchdog: could not stat heartbeat file %s: %s",
            heartbeat_path,
            exc,
        )
        return None


def check_and_terminate_if_stale(
    process: "subprocess.Popen",
    heartbeat_path: str,
    *,
    threshold_seconds: float,
    spawn_monotonic: float,
) -> Optional[StalenessVerdict]:
    """Read the heartbeat file, evaluate staleness, and -- only if stale --
    terminate `process`'s process group before returning the verdict.
    `spawn_monotonic` is the `time.monotonic()` value the caller captured
    at (or just before) `Popen(...)`. Returns None when healthy.

    A process that has already exited is never wedged, so it short-circuits
    to None. This closes a real TOCTOU window: the caller polls liveness
    first, but reading and stat'ing the heartbeat file takes time, and a
    child that finishes inside that window would otherwise be reported as
    watchdog-killed -- hiding its genuine exit code (success or failure)
    behind a bogus "no forward progress" verdict.
    """
    if process.poll() is not None:
        return None

    snapshot = read_heartbeat_snapshot(heartbeat_path)
    verdict = evaluate_staleness(
        snapshot,
        threshold_seconds=threshold_seconds,
        elapsed_since_spawn_seconds=time.monotonic() - spawn_monotonic,
        heartbeat_mtime_age_seconds=_read_heartbeat_mtime_age(heartbeat_path),
    )
    if verdict is not None:
        logger.error(
            "ActivityWatchdog: subprocess pid=%s appears wedged "
            "(reason=%s, label=%s, age=%.1fs, threshold=%.1fs) -- "
            "terminating its process group",
            verdict.pid,
            verdict.reason,
            verdict.label,
            verdict.age_seconds if verdict.age_seconds is not None else -1.0,
            threshold_seconds,
        )
        terminate_process_group(process)
    return verdict
