"""Listing SSH keys requires TOTP elevation on MCP and on the Web page,
matching REST ``GET /api/ssh-keys`` (``require_elevation()``).

Front doors, on the real app (``create_app`` via ``isolated_app``, never
~/.cidx-server):

- MCP: ``POST /mcp`` ``tools/call list_ssh_keys`` with a Bearer JWT (the
  elevation key is the token's jti).
- Web: ``GET /admin/ssh-keys`` with a Web session cookie (the elevation key
  is the session cookie value).

Elevation windows live in a real ``ElevatedSessionManager`` and TOTP
enrolment in a real ``TOTPService``, both on per-test files, installed at
the read points the gates use.  Only the elevation-enforcement switch is
patched (``self_service_elevation_harness.enforcement``).  The SSH key
listed is a real key generated by the real ``SSHKeyManager`` under the
isolated home.
"""

from __future__ import annotations

import json
import uuid
from http.cookies import SimpleCookie
from pathlib import Path
from typing import Any, Dict, Iterator

import pyotp
import pytest
from fastapi import Response
from fastapi.testclient import TestClient

from code_indexer.server.auth import dependencies
from code_indexer.server.auth.elevated_session_manager import ElevatedSessionManager
from code_indexer.server.auth.totp_service import TOTPService
from code_indexer.server.auth.user_manager import UserManager, UserRole
from code_indexer.server.mcp.auth import elevation_decorator
from code_indexer.server.mcp.handlers import ssh_keys as mcp_ssh_keys
from code_indexer.server.web import auth as web_auth
from code_indexer.server.web import mfa_routes
from code_indexer.server.web import routes as web_routes
from tests.unit.server._isolated_app import isolated_app
from tests.unit.server.self_service_elevation_harness import enforcement

PASSWORD = "Example-Ssh-Keys-Passw0rd!"
SSH_KEYS_PAGE = "/admin/ssh-keys"


@pytest.fixture(scope="module")
def client(tmp_path_factory: pytest.TempPathFactory) -> Iterator[TestClient]:
    """The real app over an isolated server home (never ~/.cidx-server)."""
    with isolated_app(tmp_path_factory.mktemp("ssh-keys-elevation-app")) as app:
        yield TestClient(app, follow_redirects=False)


@pytest.fixture
def accounts(client: TestClient) -> UserManager:
    users: UserManager = client.app.state.user_manager  # type: ignore[attr-defined]
    return users


@pytest.fixture
def esm(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> ElevatedSessionManager:
    """A real elevation-window store on this test's files, at every read point."""
    manager = ElevatedSessionManager(
        idle_timeout_seconds=300,
        max_age_seconds=1800,
        db_path=str(tmp_path / "elevated.db"),
    )
    monkeypatch.setattr(dependencies, "elevated_session_manager", manager)
    monkeypatch.setattr(elevation_decorator, "elevated_session_manager", manager)
    monkeypatch.setattr(mfa_routes, "elevated_session_manager", manager)
    return manager


@pytest.fixture
def totp(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> TOTPService:
    service = TOTPService(db_path=str(tmp_path / "mfa.db"))
    monkeypatch.setattr(mfa_routes, "_totp_service", service)
    return service


@pytest.fixture
def key_name(monkeypatch: pytest.MonkeyPatch) -> str:
    """A real managed SSH key, created where both front doors list from."""
    # The MCP handler caches its manager process-wide; resolve it afresh
    # (restored after the test) so it reads this app's server home.
    monkeypatch.setattr(mcp_ssh_keys, "_ssh_key_manager", None)
    name = f"example-deploy-key-{uuid.uuid4().hex[:8]}"
    web_routes._get_ssh_key_manager().create_key(name, key_type="ed25519")
    return name


def _admin(accounts: UserManager, totp: TOTPService) -> str:
    name = f"admin-{uuid.uuid4().hex[:8]}"
    accounts.create_user(name, PASSWORD, UserRole.ADMIN)
    secret = totp.generate_secret(name)
    assert totp.activate_mfa(name, pyotp.TOTP(secret).now())
    return name


def _member(accounts: UserManager) -> str:
    name = f"member-{uuid.uuid4().hex[:8]}"
    accounts.create_user(name, PASSWORD, UserRole.NORMAL_USER)
    return name


# ---------------------------------------------------------------------------
# MCP: POST /mcp tools/call list_ssh_keys
# ---------------------------------------------------------------------------


def _bearer(username: str, role: UserRole) -> Dict[str, str]:
    jwt = dependencies.jwt_manager
    assert jwt is not None
    token = jwt.create_token({"username": username, "role": role.value})
    jti = str(jwt.validate_token(token)["jti"])
    return {"token": token, "jti": jti}


def _list_ssh_keys(client: TestClient, token: str) -> Dict[str, Any]:
    client.cookies.clear()
    response = client.post(
        "/mcp",
        json={
            "jsonrpc": "2.0",
            "id": 1,
            "method": "tools/call",
            "params": {"name": "list_ssh_keys", "arguments": {}},
        },
        headers={"Authorization": f"Bearer {token}"},
    )
    assert response.status_code == 200, response.text
    body = response.json()
    if "error" in body:
        return {"jsonrpc_error": body["error"]}
    payload: Dict[str, Any] = json.loads(body["result"]["content"][0]["text"])
    return payload


def _listed_names(payload: Dict[str, Any]) -> list:
    return [k["name"] for k in payload.get("managed", [])]


def test_mcp_list_without_elevation_is_refused(
    client, accounts, esm, totp, key_name
) -> None:
    admin = _admin(accounts, totp)
    creds = _bearer(admin, UserRole.ADMIN)
    with enforcement(True):
        payload = _list_ssh_keys(client, creds["token"])

    assert payload.get("error") == "elevation_required", payload
    assert key_name not in json.dumps(payload)


def test_mcp_list_with_elevation_lists_keys(
    client, accounts, esm, totp, key_name
) -> None:
    admin = _admin(accounts, totp)
    creds = _bearer(admin, UserRole.ADMIN)
    esm.create(
        session_key=creds["jti"], username=admin, elevated_from_ip=None, scope="full"
    )
    with enforcement(True):
        payload = _list_ssh_keys(client, creds["token"])

    assert payload.get("success") is True, payload
    assert key_name in _listed_names(payload)


def test_mcp_list_with_enforcement_off_lists_keys(
    client, accounts, esm, totp, key_name
) -> None:
    admin = _admin(accounts, totp)
    creds = _bearer(admin, UserRole.ADMIN)
    with enforcement(False):
        payload = _list_ssh_keys(client, creds["token"])

    assert payload.get("success") is True, payload
    assert key_name in _listed_names(payload)


def test_mcp_list_by_non_admin_is_refused(
    client, accounts, esm, totp, key_name
) -> None:
    member = _member(accounts)
    creds = _bearer(member, UserRole.NORMAL_USER)
    esm.create(
        session_key=creds["jti"], username=member, elevated_from_ip=None, scope="full"
    )
    with enforcement(False):
        payload = _list_ssh_keys(client, creds["token"])

    assert payload.get("success") is not True, payload
    assert key_name not in json.dumps(payload)


# ---------------------------------------------------------------------------
# Web: GET /admin/ssh-keys
# ---------------------------------------------------------------------------


def _session_cookie(username: str, role: UserRole) -> str:
    response = Response()
    web_auth.get_session_manager().create_session(response, username, role.value)
    cookie: SimpleCookie = SimpleCookie()
    cookie.load(response.headers["set-cookie"])
    return cookie[web_auth.SESSION_COOKIE_NAME].value


def _get_page(client: TestClient, cookie: str):  # type: ignore[no-untyped-def]
    client.cookies.clear()
    client.cookies.set(web_auth.SESSION_COOKIE_NAME, cookie)
    try:
        return client.get(SSH_KEYS_PAGE)
    finally:
        client.cookies.clear()


def test_web_page_without_elevation_sends_admin_to_elevate(
    client, accounts, esm, totp, key_name
) -> None:
    admin = _admin(accounts, totp)
    cookie = _session_cookie(admin, UserRole.ADMIN)
    with enforcement(True):
        response = _get_page(client, cookie)

    assert response.status_code == 303, response.text[:300]
    assert response.headers["location"] == "/admin/elevate?next=%2Fadmin%2Fssh-keys"
    assert key_name not in response.text


def test_web_page_with_elevation_lists_keys(
    client, accounts, esm, totp, key_name
) -> None:
    admin = _admin(accounts, totp)
    cookie = _session_cookie(admin, UserRole.ADMIN)
    esm.create(session_key=cookie, username=admin, elevated_from_ip=None, scope="full")
    with enforcement(True):
        response = _get_page(client, cookie)

    assert response.status_code == 200, response.text[:300]
    assert key_name in response.text


def test_web_page_with_another_users_window_is_refused(
    client, accounts, esm, totp, key_name
) -> None:
    admin, other = _admin(accounts, totp), _admin(accounts, totp)
    cookie = _session_cookie(admin, UserRole.ADMIN)
    esm.create(session_key=cookie, username=other, elevated_from_ip=None, scope="full")
    with enforcement(True):
        response = _get_page(client, cookie)

    assert response.status_code == 303, response.text[:300]
    assert key_name not in response.text


def test_web_page_with_enforcement_off_lists_keys(
    client, accounts, esm, totp, key_name
) -> None:
    admin = _admin(accounts, totp)
    cookie = _session_cookie(admin, UserRole.ADMIN)
    with enforcement(False):
        response = _get_page(client, cookie)

    assert response.status_code == 200, response.text[:300]
    assert key_name in response.text


def test_web_page_for_non_admin_is_refused(
    client, accounts, esm, totp, key_name
) -> None:
    member = _member(accounts)
    cookie = _session_cookie(member, UserRole.NORMAL_USER)
    with enforcement(False):
        response = _get_page(client, cookie)

    assert response.status_code in (302, 303), response.text[:300]
    assert response.headers["location"].startswith("/login")
    assert key_name not in response.text
