"""
Pydantic models for the CIDX server API.

Contains all data models used for API requests and responses.
"""

from .branch_models import (
    BranchInfo,
    BranchListResponse,
    CommitInfo,
    IndexStatus,
    RemoteTrackingInfo,
)
from .error_models import (
    ErrorType,
    ErrorResponse,
    ValidationFieldError,
    ValidationErrorDetails,
    HTTPErrorResponse,
    DatabaseError,
    DatabaseRetryableError,
    DatabasePermanentError,
    RetryConfiguration,
    SanitizationRule,
    ErrorHandlerConfiguration,
)
from .auth import (
    LoginRequest,
    LoginResponse,
    RefreshTokenRequest,
    RefreshTokenResponse,
    UserInfo,
    CreateUserRequest,
    UpdateUserRequest,
    ChangePasswordRequest,
    UserResponse,
    MessageResponse,
    RegistrationRequest,
    PasswordResetRequest,
    CreateApiKeyRequest,
    CreateApiKeyResponse,
    ApiKeyListResponse,
    CreateMCPCredentialRequest,
    CreateMCPCredentialResponse,
    MCPCredentialListResponse,
)
from .query import (
    SemanticQueryRequest,
    QueryMetadata,
    SemanticQueryResponse,
    FTSResultItem,
    UnifiedSearchMetadata,
    UnifiedSearchResponse,
)
from .repos import (
    AddGoldenRepoRequest,
    GoldenRepoInfo,
    ActivateRepositoryRequest,
    ActivatedRepositoryInfo,
    SwitchBranchRequest,
    RepositoryInfo,
    RepositoryDetailsResponse,
    RepositoryListResponse,
    AvailableRepositoryListResponse,
    RepositorySyncResponse,
    RepositoryBranchesResponse,
    RepositoryStatistics,
    GitInfo,
    RepositoryConfiguration,
    RepositoryDetailsV2Response,
    ComponentRepoInfo,
    CompositeRepositoryDetails,
    RepositorySyncRequest,
    RepositorySyncJobResponse,
    GeneralRepositorySyncRequest,
)
from .jobs import (
    AddIndexRequest,
    AddIndexResponse,
    IndexInfo,
    IndexStatusResponse,
    JobResponse,
    JobStatusResponse,
    JobListResponse,
    JobCancellationResponse,
    JobCleanupResponse,
    SyncProgress,
    SyncJobOptions,
)

__all__ = [
    # branch_models
    "BranchInfo",
    "BranchListResponse",
    "CommitInfo",
    "IndexStatus",
    "RemoteTrackingInfo",
    # error_models
    "ErrorType",
    "ErrorResponse",
    "ValidationFieldError",
    "ValidationErrorDetails",
    "HTTPErrorResponse",
    "DatabaseError",
    "DatabaseRetryableError",
    "DatabasePermanentError",
    "RetryConfiguration",
    "SanitizationRule",
    "ErrorHandlerConfiguration",
    # auth
    "LoginRequest",
    "LoginResponse",
    "RefreshTokenRequest",
    "RefreshTokenResponse",
    "UserInfo",
    "CreateUserRequest",
    "UpdateUserRequest",
    "ChangePasswordRequest",
    "UserResponse",
    "MessageResponse",
    "RegistrationRequest",
    "PasswordResetRequest",
    "CreateApiKeyRequest",
    "CreateApiKeyResponse",
    "ApiKeyListResponse",
    "CreateMCPCredentialRequest",
    "CreateMCPCredentialResponse",
    "MCPCredentialListResponse",
    # query
    "SemanticQueryRequest",
    "QueryMetadata",
    "SemanticQueryResponse",
    "FTSResultItem",
    "UnifiedSearchMetadata",
    "UnifiedSearchResponse",
    # repos
    "AddGoldenRepoRequest",
    "GoldenRepoInfo",
    "ActivateRepositoryRequest",
    "ActivatedRepositoryInfo",
    "SwitchBranchRequest",
    "RepositoryInfo",
    "RepositoryDetailsResponse",
    "RepositoryListResponse",
    "AvailableRepositoryListResponse",
    "RepositorySyncResponse",
    "RepositoryBranchesResponse",
    "RepositoryStatistics",
    "GitInfo",
    "RepositoryConfiguration",
    "RepositoryDetailsV2Response",
    "ComponentRepoInfo",
    "CompositeRepositoryDetails",
    "RepositorySyncRequest",
    "RepositorySyncJobResponse",
    "GeneralRepositorySyncRequest",
    # jobs
    "AddIndexRequest",
    "AddIndexResponse",
    "IndexInfo",
    "IndexStatusResponse",
    "JobResponse",
    "JobStatusResponse",
    "JobListResponse",
    "JobCancellationResponse",
    "JobCleanupResponse",
    "SyncProgress",
    "SyncJobOptions",
]
