"""
Shared server-host validator.

This module is the SOLE authority for "is this a legal server `host` config
value" across every write path (ConfigService, the Web UI config route,
ServerConfigManager.validate_config, and the auto-updater's defense-in-depth
re-check). This value ultimately flows into privileged system-service
configuration that is generated by simple text substitution, so it must be
restricted to a single safe token: no whitespace, no line breaks, no shell
or config metacharacters.

Accepted forms: an IPv4 literal, an IPv6 literal, or a DNS hostname
(including "localhost"). "0.0.0.0" and "::" are valid, real, currently-used
values and must keep validating. Hostname labels follow RFC 1123 but may also
contain "_" (e.g. "node_1.example.internal"), and a single trailing root dot
("host.example.com.") is accepted -- both were valid values before this
validator existed. A value made only of numeric labels (decimal or 0x/0X
hex) must be a canonical IP literal: short, octal, hex and single-integer
forms ("127.1", "0177.0.0.1", "0x7f.0.0.1", "2130706433", "1.2.3") are
rejected because the resolver binds them to a different-looking address,
and so is a trailing-dot form ("127.0.0.1.") because it does not resolve.
Labels that start with a digit but contain letters ("3com.example") remain
valid hostnames.

Rejected: whitespace of any kind (including newline/carriage-return/tab),
control characters, quotes, "=", ";", "/", "$", backtick, backslash, and "%"
(IPv6 zone/scope-id syntax, e.g. "fe80::1%eth0" -- this config key has no
notion of a network interface scope).

normalize_server_host() is the single normalisation step every write path
uses: surrounding whitespace is stripped ONCE, and the stripped value is the
one validated and stored.
"""

import ipaddress
import re
from typing import Optional

# Character-set gate: the ONLY characters a legal host value may contain.
# This is the primary safety check, so it uses re.fullmatch rather than
# match()/search() with a trailing "$" anchor: "$" alone matches immediately
# before a trailing line break, which would let a multi-line value slip
# through a search()-with-"$" check. fullmatch has no such gap.
_ALLOWED_CHARS_RE = re.compile(r"[A-Za-z0-9.:_-]+")

# RFC 1123 hostname maximum total length.
_MAX_HOST_LENGTH = 253

# Hostname label grammar: 1-63 chars of alphanumerics and "_", hyphens
# allowed only in the interior (never leading or trailing).
_LABEL_RE = re.compile(r"[A-Za-z0-9_]([A-Za-z0-9_-]{0,61}[A-Za-z0-9_])?")

# A label the resolver may interpret as part of a numeric IPv4 address:
# decimal digits, or a 0x/0X hex form.
_NUMERIC_LABEL_RE = re.compile(r"[0-9]+|0[xX][0-9A-Fa-f]*")


def is_valid_server_host(host: object) -> bool:
    """Return True iff `host` is a legal server host value.

    See module docstring for accepted/rejected forms.
    """
    if not isinstance(host, str):
        return False
    if not host or len(host) > _MAX_HOST_LENGTH:
        return False
    if not _ALLOWED_CHARS_RE.fullmatch(host):
        return False

    # Semantics check #1: IPv4/IPv6 literal (covers "0.0.0.0" and "::").
    try:
        ipaddress.ip_address(host)
        return True
    except ValueError:
        pass

    # Semantics check #2: hostname grammar. A single trailing root dot
    # denotes a fully-qualified name and is not an empty label.
    fully_qualified = host.endswith(".")
    name = host[:-1] if fully_qualified else host
    labels = name.split(".")
    if not all(_LABEL_RE.fullmatch(label) for label in labels):
        return False
    # A name made only of numeric labels (decimal or 0x/0X hex) must be a
    # canonical IP literal, which semantics check #1 already accepted. The
    # resolver expands short/octal/hex/integer forms ("127.1",
    # "0x7f.0.0.1", "2130706433" -> 127.0.0.1; "1.2.3" -> 1.2.0.3), so the
    # bound address would differ from the text, and with a trailing dot
    # ("127.0.0.1.") it cannot be resolved at all.
    if all(_NUMERIC_LABEL_RE.fullmatch(label) for label in labels):
        return False
    return True


def normalize_server_host(host: object, *, current_host: Optional[str] = None) -> str:
    """Return the stripped host after validating it; raise ValueError if it
    is not a legal server host value.

    Every write path (Web UI config section, ConfigService) uses this so the
    value that is validated is exactly the value that is stored. Only
    surrounding whitespace is removed -- interior whitespace or line breaks
    still fail validation.

    current_host: the host value currently persisted. When the stripped
    value equals it, the host is not being changed, so it is returned
    without re-validation -- a host persisted before this validator existed
    must not block saves that leave it untouched. Only a CHANGE is
    validated.
    """
    if not isinstance(host, str):
        raise ValueError(f"Invalid server host: must be a string -- got {host!r}")
    stripped = host.strip()
    if current_host is not None and stripped == current_host:
        return stripped
    validate_server_host(stripped)
    return stripped


def validate_server_host(host: object) -> None:
    """Raise ValueError when `host` is not a legal server host value.

    See module docstring for accepted/rejected forms.
    """
    if not is_valid_server_host(host):
        raise ValueError(
            "Invalid server host: must be an IPv4/IPv6 address or a hostname "
            "(letters, digits, hyphens, underscores and dots only, optionally "
            "ending in a single trailing dot); a value made only of numeric "
            "labels must be a canonical IPv4 address such as 192.0.2.10 -- "
            f"got {host!r}"
        )
