"""
Shared server-host validator.

This module is the SOLE authority for "is this a legal server `host` config
value" across every write path (ConfigService, the Web UI config route,
ServerConfigManager.validate_config, and the auto-updater's defense-in-depth
re-check). This value ultimately flows into privileged system-service
configuration that is generated by simple text substitution, so it must be
restricted to a single safe token: no whitespace, no line breaks, no shell
or config metacharacters.

Accepted forms: an IPv4 literal, an IPv6 literal, or an RFC 1123 hostname
(including "localhost"). "0.0.0.0" and "::" are valid, real, currently-used
values and must keep validating.

Rejected: whitespace of any kind (including newline/carriage-return/tab),
control characters, quotes, "=", ";", and "%" (IPv6 zone/scope-id syntax,
e.g. "fe80::1%eth0" -- this config key has no notion of a network interface
scope).
"""

import ipaddress
import re

# Character-set gate: the ONLY characters a legal host value may contain.
# This is the primary safety check, so it uses re.fullmatch rather than
# match()/search() with a trailing "$" anchor: "$" alone matches immediately
# before a trailing line break, which would let a multi-line value slip
# through a search()-with-"$" check. fullmatch has no such gap.
_ALLOWED_CHARS_RE = re.compile(r"[A-Za-z0-9.:_-]+")

# RFC 1123 hostname maximum total length.
_MAX_HOST_LENGTH = 253

# RFC 1123 hostname label grammar: 1-63 chars, alphanumeric, hyphens allowed
# only in the interior (never leading or trailing).
_LABEL_RE = re.compile(r"[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?")


def is_valid_server_host(host: object) -> bool:
    """Return True iff `host` is a legal server host value.

    See module docstring for accepted/rejected forms.
    """
    if not isinstance(host, str):
        return False
    if not host or len(host) > _MAX_HOST_LENGTH:
        return False
    if not _ALLOWED_CHARS_RE.fullmatch(host):
        return False

    # Semantics check #1: IPv4/IPv6 literal (covers "0.0.0.0" and "::").
    try:
        ipaddress.ip_address(host)
        return True
    except ValueError:
        pass

    # Semantics check #2: RFC 1123 hostname grammar.
    labels = host.split(".")
    return all(_LABEL_RE.fullmatch(label) for label in labels)


def validate_server_host(host: object) -> None:
    """Raise ValueError when `host` is not a legal server host value.

    See module docstring for accepted/rejected forms.
    """
    if not is_valid_server_host(host):
        raise ValueError(
            "Invalid server host: must be an IPv4/IPv6 address or an RFC "
            "1123 hostname (letters, digits, hyphens, dots only) -- got "
            f"{host!r}"
        )
