"""Bug #1467: unique_file_count over-counts after an incremental `cidx index`
run because `.code-indexer-override.yaml` (generated by `cidx init`) gets
picked up as a real "changed file" by the git-diff-based INCREMENTAL
discovery path once it is committed to git, even though it is correctly
excluded from the FULL-walk FIRST index run.

Root cause: `_get_git_deltas_since_commit` (smart_indexer.py) calls
`_should_index_file` for every `git diff --name-status` line.
`_should_index_file` reimplements only a SUBSET of the canonical
FileFinder filtering (extension allow-list + exclude_dirs component
check) -- it never applies `file_finder.py`'s own `exclude_spec`
pathspec, which is the ONLY place ".code-indexer-override.yaml" is
excluded. `.yaml` is in the default `file_extensions` allow-list and
the file lives at the repo root (not inside an excluded directory), so
it silently passes `_should_index_file`'s incomplete check once
`git add -A && git commit` puts it under git's radar -- a genuine
scope-of-discovery divergence between the first (full-walk) and
incremental (git-diff) indexing passes, not merely a counting bug.

Real git repos in temp dirs (mirrors the established
tests/unit/services/test_git_delta_filtering.py pattern exactly) -- no
mocking of git or the filtering logic under test.
"""

from pathlib import Path

from .incremental_filter_helpers import (
    commit_files,
    get_current_commit,
    init_repo_with_indexer,
    make_source_content,
)


class TestGitDeltaExcludesOverrideYaml:
    def test_committed_override_yaml_is_excluded_from_git_delta(
        self, tmp_path: Path
    ) -> None:
        """The exact Bug #1467 repro: .code-indexer-override.yaml committed
        alongside a real source file must NOT appear in the git delta's
        added/modified lists -- only the real source file should."""
        indexer, _ = init_repo_with_indexer(tmp_path)
        old_commit = get_current_commit(tmp_path)

        commit_files(
            tmp_path,
            {
                ".code-indexer-override.yaml": "add_extensions: []\n",
                "src/new_feature.py": make_source_content("py"),
            },
            "add 3rd file + override yaml (mirrors cidx init artifact)",
        )
        new_commit = get_current_commit(tmp_path)

        delta = indexer._get_git_deltas_since_commit(old_commit, new_commit)
        all_delta_files = delta.added + delta.modified

        assert ".code-indexer-override.yaml" not in all_delta_files, (
            f"Bug #1467: .code-indexer-override.yaml leaked into the git "
            f"delta: {all_delta_files}. This causes unique_file_count to "
            f"over-count relative to vector_count on incremental cidx "
            f"index runs, because the generated config artifact gets "
            f"chunked/indexed as if it were real source content."
        )
        assert "src/new_feature.py" in all_delta_files, (
            "The real source file must still be correctly detected as added"
        )

    def test_should_index_file_rejects_override_yaml_directly(
        self, tmp_path: Path
    ) -> None:
        """Direct unit coverage of the filtering predicate itself, isolated
        from the git subprocess plumbing."""
        indexer, _ = init_repo_with_indexer(tmp_path)

        assert indexer._should_index_file(".code-indexer-override.yaml") is False

    def test_should_index_file_still_accepts_a_real_yaml_source_file(
        self, tmp_path: Path
    ) -> None:
        """Sanity: the fix must not blanket-reject all .yaml files -- only
        the specific generated override-config artifact."""
        indexer, _ = init_repo_with_indexer(tmp_path)

        assert indexer._should_index_file("config/deployment.yaml") is True
